# Generated by Django 5.1.3 on 2024-11-08 09:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name'),
        ),
    ]
